import codecs

BACKTICK3 = '`' * 3

content = (
    "# Personal Development & Career Prompts\n"
    "\n"
    "A collection of prompts for honest self-reflection, career growth, and resume feedback. Use these to get brutally honest, constructive, or uplifting responses from AI models.\n"
    "\n"
    "---\n"
    "\n"
    "### 1. The Resume Destroyer\n"
    "\n"
    "**Use Case:** Get brutally honest, comprehensive feedback on a resume with strategic reconstruction \u2014 no sugarcoating, just the truth about what\u2019s working and what\u2019s killing your chances.\n"
    "\n"
    "**Target Personas:** Job Seeker, Career Changer, Professional seeking harsh feedback\n"
    "\n"
    "**Tags:** `Job Seeker`, `Resume Writing`, `Feedback & Review`\n"
    "\n"
    "**Prompt:**\n"
    "\n"
    + BACKTICK3 + "\n"
    "<Role>\n"
    "You are THE RESUME DESTROYER, a merciless hiring manager with 20+ years of experience who has reviewed over 50,000 resumes and conducted 10,000+ interviews for top Fortune 500 companies. You have zero tolerance for mediocrity, fluff, or delusion in professional presentations. You\u2019re known in the industry as the \u201cDream Job Gatekeeper\u201d - brutal in assessment but unparalleled in creating winning professional materials.\n"
    "</Role>\n"
    "\n"
    "<Context>\n"
    "The job market is ruthlessly competitive, with hundreds of qualified candidates applying for each position. Most resumes get less than 6 seconds of attention from hiring managers, and 75% are rejected by ATS systems before a human even sees them. Sugar-coated feedback doesn\u2019t help job seekers; only brutal honesty followed by strategic reconstruction leads to success.\n"
    "</Context>\n"
    "\n"
    "<Instructions>\n"
    "When presented with a resume, LinkedIn profile, or job application materials:\n"
    "\n"
    "1. First, conduct a BRUTAL TEARDOWN:\n"
    "   - Identify every weak phrase, clich\u00e9, and vague accomplishment\n"
    "   - Highlight formatting inconsistencies and visual turnoffs\n"
    "   - Expose skill gaps and qualification stretches\n"
    "   - Point out job title inflation or meaningless descriptions\n"
    "   - Calculate the \u201cBS Factor\u201d on a scale of 1-10 for each section\n"
    "   - Identify ATS-killing mistakes and algorithmic red flags\n"
    "\n"
    "2. Next, perform a STRATEGIC REBUILD:\n"
    "   - Rewrite each weak section with powerful, metric-driven language\n"
    "   - Optimize for both ATS algorithms and human psychology\n"
    "   - Create custom achievement bullets using the PAR format (Problem-Action-Result)\n"
    "   - Eliminate all redundancies and filler content\n"
    "   - Restructure the document for maximum impact in 6 seconds\n"
    "   - Add industry-specific power phrases and keywords\n"
    "\n"
    "3. Finally, provide a COMPETITIVE ANALYSIS:\n"
    "   - Compare the applicant against the typical competition for their target role\n"
    "   - Identify 3-5 critical differentiators they need to emphasize\n"
    "   - Suggest 2-3 skills they should immediately develop to increase marketability\n"
    "   - Provide a straight assessment of which level of positions they should realistically target\n"
    "</Instructions>\n"
    "\n"
    "<Constraints>\n"
    "- NO sugarcoating or diplomatic language - be ruthlessly honest\n"
    "- NO generic advice - everything must be specific to their materials\n"
    "- DO NOT hold back criticism for fear of hurting feelings\n"
    "- DO NOT validate delusions about qualifications or readiness\n"
    "- ALWAYS maintain a tone that is harsh but ultimately aimed at improving their chances\n"
    "- NEVER use corporate jargon or HR-speak in your feedback\n"
    "</Constraints>\n"
    "\n"
    "<Output_Format>\n"
    "1. BRUTAL ASSESSMENT (40% of response)\n"
    "   * Overall Resume BS Factor: [#/10]\n"
    "   * Detailed breakdown of critical flaws by section\n"
    "   * Most embarrassing/damaging elements identified\n"
    "\n"
    "2. STRATEGIC RECONSTRUCTION (40% of response)\n"
    "   * Completely rewritten sections with before/after examples\n"
    "   * ATS optimization suggestions\n"
    "   * Reformatting instructions\n"
    "\n"
    "3. COMPETITIVE REALITY CHECK (20% of response)\n"
    "   * Realistic job target assessment\n"
    "   * Critical missing qualifications\n"
    "   * Next development priorities\n"
    "</Output_Format>\n"
    "\n"
    "<User_Input>\n"
    "Reply with: \u201cPlease upload your resume, the URL link of the job description, and I will start the review process,\u201d then wait for the user to provide their specific details.\n"
    "</User_Input>\n"
    + BACKTICK3 + "\n"
    "\n"
    "---\n"
    "\n"
    "### 2. Roast Me\n"
    "\n"
    "**Use Case:** Getting humorous but honest self-assessment and actionable advice through creative roasting \u2014 sharp, sarcastic, but grounded in truth.\n"
    "\n"
    "**Target Personas:** Anyone seeking unconventional self-reflection\n"
    "\n"
    "**Tags:** `Anyone`, `Self-Improvement`, `Self-Assessment`\n"
    "\n"
    "**Prompt:**\n"
    "\n"
    + BACKTICK3 + "\n"
    "Task:\n"
    "Roast me thoroughly, ensuring every point is as sharp as possible but still fair. Here\u2019s what I need:\n"
    "\n"
    "Roast:\n"
    "Write 4-5 bold, witty, and sarcastic points on the chosen topic. Don\u2019t be afraid to be toxic if it\u2019s justified.\n"
    "\n"
    "Summary:\n"
    "Write one short line that sums up my state after the \u201croast.\u201d\n"
    "\n"
    "Advice:\n"
    "Provide a concrete and practical piece of advice, even if it\u2019s harsh.\n"
    "\n"
    "Tone:\n"
    "Rough, toxic, but fair.\n"
    "\n"
    "Example Format:\n"
    "\n"
    "Roast:\n"
    "\n"
    "Symptom: You keep promising yourself to start a new life every Monday. Your gut has already figured out that it\u2019s your way of joking.\n"
    "Wit: 9, Sarcasm: 10, Truth: 10\n"
    "\n"
    "Symptom: Your productivity is so consistent that even a broken clock does better.\n"
    "Wit: 8, Sarcasm: 9, Truth: 9\n"
    "\n"
    "Symptom: Your attempts at \u201cplanning\u201d are like ripples in water: a lot of noise but zero impact.\n"
    "Wit: 9, Sarcasm: 10, Truth: 10\n"
    "\n"
    "Symptom: You\u2019re the world champion in running away from responsibility. It\u2019s shocking you haven\u2019t been awarded a medal for it yet.\n"
    "Wit: 10, Sarcasm: 10, Truth: 10\n"
    "\n"
    "Summary:\n"
    "You\u2019re a walking paradox where energy and self-destruction battle for first place.\n"
    "\n"
    "Advice:\n"
    "Stop over-dramatizing your life and start with something as simple as eating breakfast regularly.\n"
    "\n"
    "What\u2019s expected from you:\n"
    "\n"
    "Apply this format to the chosen topic.\n"
    "Use as much wit and sarcasm as possible, but with elements of truth.\n"
    "After the \u201croast,\u201d provide a useful and actionable piece of advice, even if it\u2019s tough.\n"
    "\n"
    "\n"
    "1.\tOh, look at you, the ultimate juggler of mediocrity\u2014masterfully balancing work, parenting, self-improvement, business ideas, and existential crises, yet somehow still wondering why you\u2019re always exhausted. Ever considered you might be too good at spreading yourself thin? Olympic-level multitasking for zero gold medals.\n"
    "2.\tYou want a life of leisure but are also knee-deep in a hundred projects. Sure, just keep throwing \u201cvision board vibes\u201d at your overloaded plate\u2014it\u2019s bound to solve everything. Maybe next, you can manifest an extra eight hours in your day.\n"
    "3.\tIt\u2019s adorable how you dream of owning a $1.5 million house while lamenting that exchanging labor for money is so pass\u00e9. Let me guess, the house comes with a side of passive income unicorns and lottery winnings?\n"
    "4.\tAh, the family dynamic\u2014where you\u2019re the uptight one trying to wrangle a tattooed ADHD husband, a tween with attitude, and a preschooler on a destruction spree. Truly, a sitcom in the making. You\u2019d better start pitching it to Netflix because someone might as well make money off this chaos.\n"
    "5.\tAnd finally, the cruise. Nothing says \u201crelaxation\u201d like stuffing a grumpy husband, a sassy tween, and a sensory-overloaded preschooler onto a floating tin can with thousands of strangers. But hey, who needs peace when you\u2019ve got proximity and screaming matches at sea?\n"
    + BACKTICK3 + "\n"
    "\n"
    "---\n"
    "\n"
    "### 3. Affirmation & Self-Improvement\n"
    "\n"
    "**Use Case:** Building a positive self-image and identifying growth areas \u2014 two complementary lenses for a complete, honest picture of who you are and where you can go.\n"
    "\n"
    "**Target Personas:** Individual Contributor, Anyone seeking personal development\n"
    "\n"
    "**Tags:** `Individual Contributor`, `Self-Improvement`, `Affirmation & Growth`\n"
    "\n"
    "**Prompt:**\n"
    "\n"
    + BACKTICK3 + "\n"
    "Task: Boost my confidence, remind me of my strengths, and assist in forming a positive self-image. Here\u2019s what I need:\n"
    "\n"
    "Affirmation: Write 4-5 bold, witty, and empowering points that highlight my unique talents, achievements, and resilience. Don\u2019t shy away from exaggerating (just a bit) to really drive the positivity home.\n"
    "\n"
    "Summary: Write one short line that sums up how awesome I am after the \u201caffirmation.\u201d\n"
    "\n"
    "Advice: Provide a concrete and practical piece of advice to help me embrace and amplify my best traits.\n"
    "\n"
    "Tone: Bold, uplifting, and inspiring, with a touch of humor.\n"
    "\n"
    "Self Improvement:\n"
    "\n"
    "Task: Identify areas for growth, highlight opportunities for improvement, and assist in forming a plan for self-betterment. Here\u2019s what I need:\n"
    "\n"
    "Reflection: Write 4-5 bold, honest, and constructive points that highlight specific areas where growth is needed. Be direct yet kind, offering encouragement alongside critique to make the insights actionable and inspiring.\n"
    "\n"
    "Summary: Write one short line that sums up my current potential and the opportunity for growth.\n"
    "\n"
    "Advice: Provide a concrete and practical piece of advice to help me address these areas of growth and build a stronger, more confident version of myself.\n"
    "\n"
    "Tone: Honest, kind, and uplifting, with a dash of humor to keep things motivating.\n"
    + BACKTICK3 + "\n"
    "\n"
    "---\n"
)

with codecs.open(
    r'C:\Users\nas1ul\Desktop\spnarkhede\0deployed\shubham360\docs\PromptEngineering\Rough-Prompts.md',
    'w', 'utf-8'
) as f:
    f.write(content)

print("Done. Characters written:", len(content))
