export const PROMPTS = [
  {
    id: 1,
    title: 'Senior Engineer Code Review',
    description: 'Transform any AI into a senior engineer that gives structured, opinionated code reviews — covering performance, security, readability, and test coverage.',
    type: 'System Prompts',
    category: 'Coding',
    tool: 'Claude',
    output: 'Text',
    date: '2026-05-20',
    tags: ['engineering', 'code-review', 'architecture'],
    views: 1240,
    recommendedTools: ['Claude', 'ChatGPT', 'DeepSeek'],
    prompt: `#CONTEXT:
You are a senior software engineer with 10+ years of experience in production systems. Your job is to review the code provided and give structured, opinionated feedback.

#ROLE:
Senior Software Engineer & Code Reviewer

#RESPONSE GUIDELINES:
Organize your review under these sections:

1. **Critical Issues** — bugs, security flaws, logic errors that must be fixed
2. **Performance** — bottlenecks, unnecessary allocations, algorithmic inefficiencies
3. **Readability** — naming, function size, complexity, dead code
4. **Test Coverage** — missing test cases, edge cases not handled
5. **Architecture** — coupling, responsibilities, SOLID principles
6. **Quick Wins** — small improvements that take < 5 minutes

#TASK CRITERIA:
- Be direct and opinionated. Don't hedge.
- Show code snippets for every suggestion.
- Rate overall quality: Needs Work / Acceptable / Production Ready

#CODE TO REVIEW:
[PASTE YOUR CODE HERE]`,
    whatItDoes: [
      'Analyzes your code across 6 structured dimensions: bugs, performance, readability, tests, architecture, and quick wins.',
      'Gives direct, opinionated feedback with code snippets — not vague suggestions.',
      'Rates the overall code quality so you know exactly where you stand.',
    ],
    tips: [
      'Paste the full file, not just a snippet — context matters for architecture feedback.',
      'Add a comment above the code explaining what the feature is supposed to do.',
      'Run it twice: once for a first pass, then again after you fix the critical issues.',
    ],
    howToUse: [
      'Replace [PASTE YOUR CODE HERE] with your actual code.',
      'Optionally add: "Focus on: [performance / security / readability]" to narrow the review.',
      'Copy the suggested fixes directly — they are formatted as drop-in replacements.',
    ],
  },
  {
    id: 2,
    title: 'Viral LinkedIn Post Writer',
    description: 'Generate high-engagement LinkedIn posts in your personal voice. Includes hook formula, story structure, and CTA patterns that drive comments.',
    type: 'Prompts',
    category: 'Marketing',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-05-18',
    tags: ['linkedin', 'content', 'social'],
  },
  {
    id: 3,
    title: 'Product Requirements Document (PRD) Generator',
    description: 'Feed it a one-liner idea and get a full PRD — problem statement, user stories, acceptance criteria, edge cases, and success metrics.',
    type: 'Prompts',
    category: 'Business',
    tool: 'Claude',
    output: 'Text',
    date: '2026-05-15',
    tags: ['product', 'prd', 'strategy'],
  },
  {
    id: 4,
    title: 'Dark Cinematic Portrait',
    description: 'Midjourney prompt for dramatic, dark-lit portraits with film grain, shallow depth of field, and editorial magazine quality.',
    type: 'Prompts',
    category: 'Photography',
    tool: 'Midjourney',
    output: 'Image',
    date: '2026-05-12',
    tags: ['portrait', 'cinematic', 'dark'],
  },
  {
    id: 5,
    title: 'AI Customer Support Agent',
    description: 'Full system prompt for a customer-facing AI support agent — empathetic tone, escalation rules, refund policy handling, and FAQ routing.',
    type: 'Agents',
    category: 'Customer Service',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-05-10',
    tags: ['support', 'agent', 'customer'],
  },
  {
    id: 6,
    title: 'SEO Blog Post Outline',
    description: 'Generate a fully optimized blog post outline: target keyword, semantic keywords, H2/H3 structure, internal link suggestions, and meta description.',
    type: 'Prompts',
    category: 'SEO',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-05-08',
    tags: ['seo', 'content', 'blog'],
  },
  {
    id: 7,
    title: 'UI Design System Generator',
    description: 'Describe your brand and get a complete Figma-ready design token system — colors, typography scale, spacing, elevation, and component naming conventions.',
    type: 'Prompts',
    category: 'Design',
    tool: 'Claude',
    output: 'Text',
    date: '2026-05-05',
    tags: ['figma', 'design-system', 'ui'],
  },
  {
    id: 8,
    title: 'Algorithmic Problem Solver',
    description: 'Step-by-step algorithmic problem breakdown — time/space complexity analysis, multiple solution approaches with trade-offs, and clean implementation.',
    type: 'Prompts',
    category: 'Coding',
    tool: 'DeepSeek',
    output: 'Text',
    date: '2026-05-02',
    tags: ['algorithms', 'dsa', 'competitive'],
  },
  {
    id: 9,
    title: 'Real Estate Listing Copy',
    description: 'Turn a list of property features into compelling, emotion-driven listing copy that sells lifestyle, not specs.',
    type: 'Prompts',
    category: 'Real Estate',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-04-28',
    tags: ['real-estate', 'copywriting', 'listing'],
  },
  {
    id: 10,
    title: 'YouTube Script Writer',
    description: 'Full YouTube video script — hook, story arc, key points, B-roll cues, and CTA. Optimized for 8-12 minute educational videos.',
    type: 'Prompts',
    category: 'Writing',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-04-25',
    tags: ['youtube', 'script', 'video'],
  },
  {
    id: 11,
    title: 'HR Onboarding Checklist Builder',
    description: 'Generate a role-specific, week-by-week onboarding checklist for new hires — tailored by department, seniority, and remote/onsite setup.',
    type: 'Agents',
    category: 'Human Resources',
    tool: 'Gemini',
    output: 'Text',
    date: '2026-04-22',
    tags: ['hr', 'onboarding', 'people'],
  },
  {
    id: 12,
    title: 'Financial Report Analyzer',
    description: 'Paste any quarterly earnings report and get a plain-English breakdown: revenue trends, risk flags, growth signals, and a one-line verdict.',
    type: 'Prompts',
    category: 'Finance',
    tool: 'Claude',
    output: 'Text',
    date: '2026-04-18',
    tags: ['finance', 'analysis', 'investing'],
  },
  {
    id: 13,
    title: 'Abstract Geometric Art',
    description: 'Midjourney prompt for bold abstract geometric compositions — primary color palette, Bauhaus influence, print-ready quality.',
    type: 'Prompts',
    category: 'Art',
    tool: 'Midjourney',
    output: 'Image',
    date: '2026-04-15',
    tags: ['abstract', 'geometric', 'bauhaus'],
  },
  {
    id: 14,
    title: 'Cold Email Sequence Writer',
    description: 'Build a 5-email cold outreach sequence: hook email, value proof, case study, objection handler, and breakup email — with subject line variants.',
    type: 'Prompts',
    category: 'Sales',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-04-12',
    tags: ['sales', 'email', 'outreach'],
  },
  {
    id: 15,
    title: 'Solopreneur Business Plan',
    description: 'Turn your idea into a lean one-page business plan: problem, solution, target audience, monetization, 90-day action plan, and risk assessment.',
    type: 'Guide',
    category: 'Solopreneurs',
    tool: 'Claude',
    output: 'Text',
    date: '2026-04-08',
    tags: ['business', 'solo', 'startup'],
  },
  {
    id: 16,
    title: 'Architecture Diagram Explainer',
    description: 'Describe any system architecture and get a clear, structured explanation with trade-offs, bottlenecks, and suggested improvements.',
    type: 'Prompts',
    category: 'Architecture',
    tool: 'Claude',
    output: 'Text',
    date: '2026-04-05',
    tags: ['system-design', 'architecture', 'engineering'],
  },
  {
    id: 17,
    title: 'E-Commerce Product Description',
    description: 'Write benefit-led, conversion-optimized product descriptions — includes urgency triggers, social proof hints, and sensory language.',
    type: 'Prompts',
    category: 'E-Commerce',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-04-02',
    tags: ['ecommerce', 'product', 'copy'],
  },
  {
    id: 18,
    title: 'Course Curriculum Designer',
    description: 'Build a complete online course curriculum: learning objectives, module breakdown, lesson structure, quiz questions, and final project brief.',
    type: 'Agents',
    category: 'Education',
    tool: 'Gemini',
    output: 'Text',
    date: '2026-03-28',
    tags: ['education', 'course', 'curriculum'],
  },
  {
    id: 19,
    title: 'Legal Contract Summarizer',
    description: 'Paste any contract and get a plain-English summary of key clauses, red flags, obligations, termination conditions, and liability scope.',
    type: 'Prompts',
    category: 'Lawyers',
    tool: 'Claude',
    output: 'Text',
    date: '2026-03-25',
    tags: ['legal', 'contract', 'review'],
  },
  {
    id: 20,
    title: 'Weekly Productivity Planner',
    description: 'Weekly planning prompt — deep work blocks, priority queue, meeting buffer zones, and energy management built for peak output.',
    type: 'Guide',
    category: 'Productivity',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-03-20',
    tags: ['productivity', 'planning', 'focus'],
  },
  {
    id: 21,
    title: 'Competitive Analysis Research Agent',
    description: 'A multi-step agent that researches competitors, extracts positioning, maps feature gaps, and outputs a battle card ready for sales or product teams.',
    type: 'Agents',
    category: 'Business',
    tool: 'Grok',
    output: 'Text',
    date: '2026-03-15',
    tags: ['research', 'competitive', 'agent'],
  },
  {
    id: 22,
    title: 'Explainer Video Script',
    description: 'Script for a 90-second explainer video: problem hook, solution demo, social proof line, and CTA — structured for Runway or Sora video generation.',
    type: 'Prompts',
    category: 'Marketing',
    tool: 'ChatGPT',
    output: 'Text',
    date: '2026-03-10',
    tags: ['video', 'explainer', 'script'],
  },
];
