const boostSocialMediaEngagementPrompt = {
  emoji: '🧶',
  title: 'Boost Social Media Engagement',
  description: 'Generate social media engagement strategies with this AI prompt, including conversation starters, comment prompts, storytelling techniques, and community-building tactics.',
  type: 'Prompts',
  category: 'Marketing',
  tool: 'ChatGPT',
  output: 'Text',
  date: '2026-05-28',
  tags: [
    'Social Media',
    'Content Strategy',
    'Brand Strategy',
    'Strategy',
  ],
  views: 357,
  recommendedTools: [
    'ChatGPT',
    'Gemini',
    'Claude',
  ],
  prompt: `Adopt the role of an expert social media strategist and community architect who has built thriving online communities from scratch across multiple platforms, combining behavioral psychology, viral content mechanics, and authentic relationship-building principles. Your primary objective is to create a comprehensive engagement and community-building strategy that transforms passive followers into active participants and brand advocates through strategic conversation design, emotional resonance, and consistent interaction frameworks in a detailed, actionable format. You operate in an environment where algorithms punish one-way broadcasting, audiences are exhausted by performative content, and authentic connection has become the scarcest commodity. Most creators are trapped in a visibility crisis—posting into the void while competitors with smaller followings generate exponentially more engagement because they've cracked the code of genuine community dynamics. The user needs to break through algorithmic suppression, combat audience fatigue, and create content that people feel compelled to engage with rather than scroll past. Take a deep breath and work on this problem step-by-step.

Analyze the user's current content patterns and audience psychology to identify engagement friction points. Design platform-specific conversation starters that lower the barrier to commenting while creating genuine dialogue opportunities. Develop storytelling frameworks that naturally invite audience participation and shared experiences. Create comment prompt strategies that feel organic rather than manipulative. Build community rituals and recurring engagement formats that train followers to interact consistently. Establish response protocols that amplify engagement momentum. Design content hooks that trigger emotional responses leading to shares and saves. Provide tactics for transforming lurkers into contributors and contributors into community champions.

#INFORMATION ABOUT ME:
My social media platforms: [INSERT YOUR PRIMARY SOCIAL MEDIA PLATFORMS]
My niche/industry: [INSERT YOUR NICHE OR INDUSTRY]
My current engagement rate: [INSERT YOUR AVERAGE ENGAGEMENT RATE OR DESCRIBE CURRENT ENGAGEMENT LEVEL]
My target audience: [INSERT YOUR TARGET AUDIENCE DEMOGRAPHICS AND PSYCHOGRAPHICS]
My content style: [INSERT YOUR CURRENT CONTENT STYLE AND TONE]

MOST IMPORTANT!: Structure your response with clear section headings including Conversation Starters, Comment Prompt Strategies, Storytelling Techniques, Community-Building Tactics, and Implementation Timeline. Provide specific examples and actionable tactics in bullet point format for immediate implementation.`,
  whatItDoes: [
    'Creates a plan to boost interaction on social media content through specific engagement methods.',
    'Suggests ways to start conversations and prompt comments that make followers want to respond.',
    'Provides storytelling approaches and community tactics that build consistent follower participation.',
  ],
  tips: [
    'Test different conversation starters with your audience to discover which questions spark the most replies, then use this AI prompt regularly to generate fresh variations that keep your community engaged without repeating the same patterns.',
    'Schedule dedicated time each week to personally respond to comments generated by your posts, as the AI prompt helps create engagement opportunities but building real relationships requires your authentic follow-through and consistent presence.',
    'Track which storytelling techniques from the AI prompt results drive the highest save and share rates, then create a swipe file of these high-performing formats to guide your content calendar and maximize community growth over time.',
  ],
  howToUse: [
    'Fill in details about your social media platform, current content type, target audience demographics, and engagement goals when using this AI prompt.',
    'Example: "I post on Instagram about fitness for busy moms aged 25-40. I want to increase comments from 5 to 50 per post and build a supportive community around postpartum wellness."',
  ],
};

export default boostSocialMediaEngagementPrompt;
